version: "2"

services:
  backend:
    container_name: backend-reflex
    build: ./server
    restart: always
    volumes:
      - "./server:/Backend"
      - /Backend/node_modules
    ports:
      - "5000:5000"

  client:
    container_name: client-reflex
    build: ./client
    stdin_open: true
    restart: always
    volumes:
      - "./client:/App"
    ports:
      - "3000:3000"

  web-server:
    container_name: web-server-reflex
    build: ./web-server
    restart: always
    volumes:
      - ./web-server/conf.d:/etc/nginx/conf.d
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - mysql
      - mongo

  mysql:
    container_name: primary-reflex
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"

  mongo:
    container_name: secondary-reflex
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - "27017:27017"
