USE REFLEX;
CREATE TABLE Teacher (
  Email VARCHAR(45) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  Handle VARCHAR(40) NOT NULL,
  UserName VARCHAR(50) NOT NULL,
  Biography VARCHAR(400) NOT NULL DEFAULT 'I am a teacher!',
  PRIMARY KEY (Handle),
  ProfilePicture VARCHAR(15) DEFAULT 'boy(3).svg',
  JoinedWebsite DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE INDEX EmailUNIQUE (Email ASC)
);
CREATE TABLE Course (
  _id INT NOT NULL AUTO_INCREMENT,
  Teacher_Handle VARCHAR(40) NOT NULL,
  Description VARCHAR(400),
  Name VARCHAR(50) NOT NULL,
  Created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DisplayPicture VARCHAR(15) DEFAULT '1.jpg',
  PRIMARY KEY (_id, Teacher_Handle),
  CONSTRAINT HandleCourse FOREIGN KEY (Teacher_Handle) REFERENCES Teacher (Handle) ON DELETE CASCADE ON UPDATE CASCADE
);